Updated FAQ - how to upload pictures to remote server
PhotoboothProject/photobooth pull request #127
Opened 2023-02-01 13:21 UTC by phl25

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
Updated the FAQ with a section about how to upload pictures to a remote server after the picture has been taken with the Photobox

#### Is there anything you'd like reviewers to focus on?

2023-02-01 16:39 UTC, andi34 requested changes

2023-02-01 16:39 UTC, andi34 commented on faq/faq.md
> +## How to:
`####`

2023-02-01 16:39 UTC, andi34 commented on faq/faq.md
> +## Usecase:
`####`

2023-02-01 20:13 UTC, phl25 commented
Updated with the requested change

2023-02-02 15:08 UTC, andi34 approved these changes

2023-02-02 15:10 UTC, merged