Empty test commit
PhotoboothProject/photobooth pull request #45
Opened 2022-09-24 11:43 UTC by fmiccolis

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
This new feature allow the guests to see themselves on the live preview with the frame on top so they can positionate according to it.
The frame is shown on both picture and collage if they have the option enabled (in the case of collage has to be "always").
The other restriction is that the preview has to be in a "contain" object-fit to maintain the proportion of both preview and frame.

#### Is there anything you'd like reviewers to focus on?
I'm sorry for the commit messages!

2022-09-29 09:35 UTC, andi34 requested changes

2022-09-29 09:35 UTC, andi34 commented on src/sass/classic_style.scss
> +#collage--frame {
Definition should be moved to
`src/sass/partials/_video_preview.scss`

2022-09-30 14:44 UTC, andi34 commented on lib/config.php
> +if (!empty($config['picture']['frame'])) {
Defined some lines up already

2022-10-03 06:02 UTC, andi34 approved these changes

2022-11-28 14:51 UTC, up-87 approved these changes

2022-11-28 15:35 UTC, andi34 commented
I'll repush and merge later in the evening or tomorrow morning

2022-11-29 07:18 UTC, merged