feat: Add sound support
PhotoboothProject/photobooth pull request #587
Opened 2024-01-31 22:05 UTC by dadav

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added some basic sounds and the required code. But it's not working yet.

See #310

2024-02-02 21:16 UTC, dadav commented
Summary:
- Add sounds for countdown + cheese
- Sounds are disable by default
- Every group of sounds is deactivateable (countdown, cheese)
- The english sounds are used as a fallback (can be deactivated)
- Custom sounds can be added in `/private/sounds`

2024-02-03 08:16 UTC, andi34 requested changes

2024-02-03 08:16 UTC, andi34 commented on resources/lang/en.json
https://github.com/andi34/i18n-editor-release

Should be edited using the i18n editior

2024-02-03 08:16 UTC, andi34 commented on docs/configuration/sounds.md
> +If you have speakers connected to your photobox, you can enable the sound
Photobooth instead of photobox

2024-02-03 08:16 UTC, andi34 commented on resources/lang/de.json
Need to be added via Crowdin.

2024-02-03 09:18 UTC, dadav commented on resources/lang/en.json
Ok, I've used the editor now.

2024-02-03 09:19 UTC, dadav commented on resources/lang/de.json
Okay, I've removed my changes.

2024-02-03 09:48 UTC, andi34 requested changes

2024-02-03 09:48 UTC, andi34 commented on resources/lang/en.json
There's a lot strings removed, by accident I guess

2024-02-03 10:21 UTC, dadav commented on resources/lang/en.json
Hm, I've used the editor, don't know what went wrong

2024-02-03 11:16 UTC, dadav commented on resources/lang/en.json
I opened the project and saved it again, so it would adjust the formatting.

2024-02-03 12:16 UTC, andi34 commented on resources/lang/en.json
Mh... There's a lot of manual entries removed which shouldn't. Some of the formatting earlier broke and removed it?

2024-02-03 13:02 UTC, dadav commented on resources/lang/en.json
I think now it should be fine. It somehow didnt handle the manual additions well.

2024-02-11 10:45 UTC, andi34 approved these changes

2024-02-11 10:45 UTC, merged