remove reference to dev mode
PhotoboothProject/photobooth pull request #71
Opened 2022-10-26 17:55 UTC by modularTaco

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

According to https://github.com/PhotoboothProject/photobooth/issues/11 the dev mode has been removed. Instead the same result of setting photobooth to dev mode can be achieved by setting the loglevel to 1.  
So i removed the reference to the dev mode in the FAQ, as this setting is not available anymore.  
Further more the log level can be set in the basic administration mode already, no need to enable the expert view

#### Is there anything you'd like reviewers to focus on?

2022-10-26 18:44 UTC, andi34 requested changes
Thanks for the finding! Could you please adjust mentioned note?

2022-10-26 18:44 UTC, andi34 commented on faq/faq.md
> +- Set Photobooth Log Level to 1. (admin screen -> general section)
to 1 (or above).

2022-10-26 18:48 UTC, modularTaco commented
> Thanks for the finding! Could you please adjust mentioned note?

Sure 👍

2022-10-26 18:55 UTC, modularTaco commented
Hey @andi34 , [here](https://github.com/PhotoboothProject/photobooth/blob/dev/resources/lang/en.json#L313) is also a reference to dev mode. Can the language file be modified here in git directly, or has this to be done in the translation tool?

2022-10-26 19:30 UTC, andi34 commented
English can be modified here :)

2022-10-29 11:33 UTC, andi34 commented
Great! Thanks a lot!

Could you rebase your changes on top of latest dev branch please to avoid the commits `Merge branch 'PhotoboothProject:dev' into patch-2` ?

2022-10-29 13:56 UTC, modularTaco commented
> Great! Thanks a lot!
> 
> Could you rebase your changes on top of latest dev branch please to avoid the commits `Merge branch 'PhotoboothProject:dev' into patch-2` ?

Won't they be gone already if you merge the pr and squash the commits?  
But sure, i rebased the branch on top of the latest commit in the dev branch

2022-10-29 14:32 UTC, merged

2022-10-29 14:34 UTC, andi34 commented
Squash merge was disabled, but enabled it and used it now =)
Thanks a lot again!