feature: collage.json generator
PhotoboothProject/photobooth pull request #762
Opened 2024-06-19 18:00 UTC by fmiccolis

#### Prerequisites checklist

- [ ] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
I've created a wysiwyg page to visually generate the collage.json file.
I've also extended the functions of the file by adding:
- background color
- placeholder image
- single image frame toggle

The image upload route is now a file upload because i give the user the possibility to upload .ttf fonts inside /private/fonts folder. The dispatch from /private/fonts and /private/images is done by checking the file type before appending the folderName.

#### Is there anything you'd like reviewers to focus on?
I need an hand from the community to test edge cases

2024-07-04 08:03 UTC, andi34 requested changes

2024-07-04 08:03 UTC, andi34 commented on src/Collage.php
> -        if ($rotate_after_creation) {
We still need this for the other layouts

2024-07-06 08:40 UTC, andi34 approved these changes

2024-07-09 21:14 UTC, andi34 commented
While saving the layout via generator the collage config should be updated too. ATM e.g. the limits are not adjusted based on the given images array and we would need to go back to the Adminpanel first and save the config again before the layout can be tested.

2024-07-10 21:28 UTC, benjaminkott commented
Hey @andi34, hey @fmiccolis a quick update.

I´ve extracted some of the changes to make the pull-request more manageable. 
This pr should now only include the collage generation.

feature: add font selector
https://github.com/PhotoboothProject/photobooth/commit/b771215d3eea7de2d95eab4128c536b43790bc03

feature: allow font uploads
https://github.com/PhotoboothProject/photobooth/commit/5ffca06db4709aa243ca916103e395d24198acc4

2024-07-11 04:11 UTC, andi34 commented
https://github.com/PhotoboothProject/photobooth/pull/709

Was reverted by accident

2024-09-11 19:50 UTC, merged